/* This file is generated by `npm run chapters:sync`. Do not edit it by hand. */
import type { ChapterConfig, ChapterSummary } from "./chapter-definition";

export const CHAPTER_IDS = ["1", "2", "3", "4", "5", "6", "7", "8", "9"] as const;
export type ChapterId = (typeof CHAPTER_IDS)[number];

export const CHAPTER_SUMMARIES = [
  { id: "1", label: "Chapter 1", shortLabel: "Chapter 1 lesson", printedRange: "printed pp.8-23" },
  { id: "2", label: "Chapter 2", shortLabel: "Chapter 2 lesson", printedRange: "printed pp.24-33" },
  { id: "3", label: "Chapter 3", shortLabel: "Chapter 3 lesson", printedRange: "printed pp.34-50" },
  { id: "4", label: "Chapter 4", shortLabel: "Chapter 4 lesson", printedRange: "printed pp.51-62" },
  { id: "5", label: "Chapter 5", shortLabel: "Chapter 5 lesson", printedRange: "printed pp.63-72" },
  { id: "6", label: "Chapter 6", shortLabel: "Chapter 6 lesson", printedRange: "printed pp.73-86" },
  { id: "7", label: "Chapter 7", shortLabel: "Chapter 7 lesson", printedRange: "printed pp.87-111" },
  { id: "8", label: "Chapter 8", shortLabel: "Chapter 8 lesson", printedRange: "printed pp.112-125" },
  { id: "9", label: "Chapter 9", shortLabel: "Chapter 9 lesson", printedRange: "printed pp.126-133" },
] as const satisfies readonly ChapterSummary[];

export function isChapterId(id: string): id is ChapterId {
  return (CHAPTER_IDS as readonly string[]).includes(id);
}

const CHAPTER_LOADERS: Record<ChapterId, () => Promise<ChapterConfig>> = {
  "1": () => import("./chapter-packages/chapter-1").then((module) => module.CHAPTER_CONFIG),
  "2": () => import("./chapter-packages/chapter-2").then((module) => module.CHAPTER_CONFIG),
  "3": () => import("./chapter-packages/chapter-3").then((module) => module.CHAPTER_CONFIG),
  "4": () => import("./chapter-packages/chapter-4").then((module) => module.CHAPTER_CONFIG),
  "5": () => import("./chapter-packages/chapter-5").then((module) => module.CHAPTER_CONFIG),
  "6": () => import("./chapter-packages/chapter-6").then((module) => module.CHAPTER_CONFIG),
  "7": () => import("./chapter-packages/chapter-7").then((module) => module.CHAPTER_CONFIG),
  "8": () => import("./chapter-packages/chapter-8").then((module) => module.CHAPTER_CONFIG),
  "9": () => import("./chapter-packages/chapter-9").then((module) => module.CHAPTER_CONFIG),
};

export function loadChapter(id: ChapterId): Promise<ChapterConfig> {
  return CHAPTER_LOADERS[id]();
}
