/* This file is generated by `npm run chapters:sync`. Do not edit it by hand. */
export const CHAPTER_IDS = ["1", "2", "3"] as const;

export type ChapterId = (typeof CHAPTER_IDS)[number];

export function isChapterId(id: string): id is ChapterId {
  return (CHAPTER_IDS as readonly string[]).includes(id);
}
