import { Chess } from "chess.js";
import type { LessonBlock, MoveReference, SourceSpan, VariationMove, VariationNode } from "./lesson-model";

const OPEN = ["d4", "Nf6", "c4", "e6", "g3", "d5", "Nf3"];
const ids = (page: number, column: "left" | "right") => `chapter1-p${page}-${column}-c`;
const ref = (source: string, lineId: string, moveIndex: number): MoveReference => ({ source, lineId, moveIndex });

function fenAfter(sequence: string[]): string {
  const chess = new Chess();
  for (const san of sequence) chess.move(san);
  return chess.fen();
}

function sourceLine(id: string, label: string, span: string, setup: string[], sans: string[]): VariationNode {
  const startFen = fenAfter(setup);
  const chess = new Chess(startFen);
  const lineMoves: VariationMove[] = sans.map((san, index) => {
    chess.move(san);
    return { id: `${id}-${index + 1}`, san, sourceToken: san, sourceSpanId: span };
  });
  return { id, label, parentLineId: null, parentPly: 0, startFen, startLabel: `Position before ${label}`, moves: lineMoves };
}

export const C_SOURCE_SPANS: SourceSpan[] = Array.from({ length: 10 }, (_, pageOffset) => {
  const page = 14 + pageOffset;
  return (["left", "right"] as const).map((column, columnOffset) => ({
    id: ids(page, column),
    status: "source-verified" as const,
    pageIndex: page - 7,
    printedPage: page,
    column,
    order: 15 + pageOffset * 2 + columnOffset,
    crop: `/source/pages/printed-${page}.png`,
    bbox: { x0: column === "left" ? 35 : 237, top: 50, x1: column === "left" ? 237 : 440, bottom: 640 },
  }));
}).flat();

export const C_LINES: VariationNode[] = [
  sourceLine("c-entry", "C) 4...c5", ids(14, "left"), OPEN, ["c5"]),
  sourceLine("c1-entry", "C1) 5...Be7", ids(14, "right"), [...OPEN, "c5", "Bg2"], ["Be7"]),
  sourceLine("c2-entry", "C2) 5...Nc6 6.O-O", ids(18, "left"), [...OPEN, "c5", "Bg2"], ["Nc6", "O-O"]),
  sourceLine("c21-entry", "C21) 6...Be7 7.dxc5 Bxc5", ids(18, "left"), [...OPEN, "c5", "Bg2", "Nc6", "O-O"], ["Be7", "dxc5", "Bxc5"]),
  sourceLine("c22-entry", "C22) 6...cxd4 7.Nxd4", ids(21, "left"), [...OPEN, "c5", "Bg2", "Nc6", "O-O"], ["cxd4", "Nxd4"]),
];

export const C_BLOCKS: LessonBlock[] = [
  { id: "c-heading", type: "heading", status: "source-verified", sourceSpanId: ids(14, "left"), text: "C) 4...c5", moveRefs: [ref("4...c5", "c-entry", 0)] },
  { id: "c-intro-left", type: "prose", status: "source-verified", sourceSpanId: ids(14, "left"), text: "This is another option that I forgot to cover in my previous 1.d4 volumes. It is not the most popular move order in Grandmaster practice, although I noticed that Aronian won some recent games with it." },
  { id: "c-intro-right", type: "prose", status: "source-verified", sourceSpanId: ids(14, "right"), text: "5.Bg2. 5.cxd5 exd5 leads to a Tarrasch Defence, but I intend to recommend something other than the g2-g3 variation against that opening, as you will see in Volume 1B. Black also has the independent alternatives of 5...Nxd5 and 5...cxd4!?. Black has two main continuations: C1) 5...Be7 and C2) 5...Nc6. 6...dxc4 leads to a branch of the Catalan covered in Chapters 6 and 7. 5...cxd4 6.O-O is also likely to transpose elsewhere: 6...Nc6 reaches C22, while 6...dxc4 leads to variation A of Chapter 6 on page 74." },
  { id: "c1-heading", type: "heading", status: "source-verified", sourceSpanId: ids(14, "right"), text: "C1) 5...Be7", moveRefs: [ref("5...Be7", "c1-entry", 0)] },
  { id: "c1-start", type: "prose", status: "source-verified", sourceSpanId: ids(14, "right"), text: "This move order was recommended by Aagaard and Ntirlis in Grandmaster Repertoire 10 - The Tarrasch Defence (abbreviated to GM 10 from now on). 6.O-O O-O 7.dxc5 Bxc5. 7...dxc4 8.Qc2 takes us a long way ahead to variation A of Chapter 16 - see page 253." },

  { id: "c1-p15-left", type: "variation", status: "source-verified", sourceSpanId: ids(15, "left"), title: "C1: 8.cxd5!", lineId: "c1-entry", text: "8.cxd5! 8.a3 was recommended by Marin in his English repertoire book, but GM 10 shows a good solution for Black. Without going into details, the fact that the knight has not yet gone to c6 helps Black. 8...exd5. A lesser option is 8...Nxd5 9.Qc2! Qe7. After 9...Qc7 10.Nc3 Nd7 11.Bd2 White is clearly better; 11...Bb4 occurred in Romanov - Ippolito, Philadelphia 2012, and 12.Rac1± would have given White an obvious advantage. 9...Be7 10.Rd1 Qa5 11.Bd2 Qc5 12.Nc3. After 12...Nxc3 13.Bxc3 Qb6 in Ladanyi - Kelemen, Budapest 2005, 14.Ne5!N would claim an overwhelming advantage. 10.a3 Nc6 11.b4 Bb6 12.Bb2 Bd7 13.e4 Nf6 14.e5 Nd5 15.Nbd2 Rac8 16.Qe4! White has a pleasant space advantage and good chances to seize the initiative on the kingside, Bezold - Lipinsky, Budapest 1997." , moveRefs: [] },
  { id: "c1-p15-right", type: "prose", status: "source-verified", sourceSpanId: ids(15, "right"), text: "9.Qc2!? An important moment. The inevitable development of the black knight to c6 will complete the transposition to the Tarrasch Defence. The queen attacks the enemy bishop while making room for the rook to go to d1 if needed. 9...Bb6. Other moves are inadvisable. 9...Qb6? should be avoided, as 10.Nc3 threatens a fork on a4; after 10...Bd7 11.Bg5 Black had serious problems with the d5-pawn in Andriessen - Rietveld, Alkmaar 1982. 9...Be7 10.Rd1 Nc6 11.Nc3 leaves Black uncomfortable because of the isolated pawn and X-ray along the d-file. 11...Qa5. After 11...Be6 12.Ng5! h6? in Izzat - Kowsarinia, Kigali 2011, 13.Bxd5!N would have won material. 12.Be3 Be6 13.a3! The black queen is unstable on a5. 13...Rac8 14.b4 Qc7 15.Rac1 a5. In Ribli - Lalk, Sarajevo 1985, White missed a powerful idea." },
  { id: "c1-p16-left", type: "prose", status: "source-verified", sourceSpanId: ids(16, "left"), text: "16.Ng5!N axb4. 16...h6 17.Nxe6 fxe6 18.Bh3 is also excellent for White. 17.Nxd5 Bxd5 18.Bxd5 Qa5. 18...bxa3 loses by force: 19.Bxf7+! Rxf7 20.Nxf7 Kxf7 21.Qb3+ Kf8 22.Bf4 Qa5 23.Qxb7+-. 19.axb4 Qxb4 20.Bb3 and White is clearly better. 10.Nc3 Nc6. 10...h6 11.Na4 Nc6 transposes to the note below. 11.Na4! The more common 11.Bg5 Be6 is analysed in GM 10. The text move has only been played once in more than thirty games, but it is most accurate because White avoids committing the bishop prematurely. 11...Bc7 is the obvious candidate and was Black's choice in the only game." },
  { id: "c1-p16-right", type: "prose", status: "source-verified", sourceSpanId: ids(16, "right"), text: "Other eleventh moves are possible. 11...Re8N 12.Nxb6 Qxb6 13.Bg5! provokes ...Ne4 to weaken the d5-pawn. After 13...Re6 14.b3 h6 15.Bc1! White will slowly establish control over d4. 11...Be6 12.Nxb6 Qxb6 13.Bg5! Ne4 14.Be3 Qa6 15.b3 Bg4 16.Qb2 Rfe8 17.Rfe1 gave White a stable positional advantage in Malaniuk - Giorgadze, Odessa 1989. 11...h6 12.Nxb6 Qxb6. 12...axb6 further weakens Black's pawns; 13.Rd1 Bg4 14.Be3 Re8 15.h3 Bxf3 16.Bxf3 Rxe3?! 17.fxe3 Qc7 18.Kg2± left Black without enough compensation in Wojtaszek - Shkapenko, Gorzow 2012. 13.b3 Rd8." },
  { id: "c1-p17-left", type: "prose", status: "source-verified", sourceSpanId: ids(17, "left"), text: "13...Be6 occurred in Gajewski - Koch, Haguenau 2013. White could have played 14.Be3!N, meeting 14...d4 with 15.Nxd4! Nxd4 16.Qb2 Nxe2+ 17.Qxe2, when the bishop pair gives White a pleasant edge. In Lazarev - T.L. Petrosian, Lausanne 2005, White should have chosen simple development: 14.Bb2 Ne4. 14...d4? just loses the pawn to 15.Rad1 Be6 16.Qd3±. 15.Rad1 Bf5 16.Nd4 Bg6 17.Qc1. 17.Nxc6 bxc6 18.Bd4 also deserves attention. 17...Rac8 18.Qa1! White has a stable advantage thanks to control of d4 and the bishop pair." },
  { id: "c1-p17-right", type: "prose", status: "source-verified", sourceSpanId: ids(17, "right"), text: "12.Be3!N. 12.Rd1 was played in Jumabayev - Senador, Al-Ain 2012, but 12...Re8N was not altogether satisfactory, so a new concept is needed. 12...Re8 13.Qd3! White prevents the possible exchange sacrifice that may be effective after 13.Rac1 Rxe3 14.fxe3 Qe7∞. A logical sequence is 13...Bg4 14.Rac1 h6. 14...Rc8 15.h3 Bh5 16.Bg5! is clearly inferior for Black. 15.Rfd1 Rac8 16.a3. White has completed development and should retain a slight but pleasant advantage. After 16...Ne7, 17.Nc3 Rcd8 18.b4 Nd7; 16...Bb5 17.Nc3 Be6 18.b4 Qd7 19.Qd2±. If 18...Bxf3, then 19.Bc5 Bd6 20.Bxd6 Rxd6 21.exf3! followed by f3-f4 puts the d-pawn under serious pressure." },
  { id: "c1-p18-left", type: "prose", status: "source-verified", sourceSpanId: ids(18, "left"), text: "After 19...b6 20.Be3± Black's pieces on the c-file have been destabilized. 20.Qd2 Bh3 21.Bh1±. The position remains complex, but White is better for sure." },

  { id: "c2-heading", type: "heading", status: "source-verified", sourceSpanId: ids(18, "left"), text: "C2) 5...Nc6 6.O-O", moveRefs: [ref("5...Nc6", "c2-entry", 0), ref("6.O-O", "c2-entry", 1)] },
  { id: "c2-intro", type: "prose", status: "source-verified", sourceSpanId: ids(18, "left"), text: "This is an important branching position, where Black's two main tries are C21) 6...Be7 and C22) 6...cxd4. 6...dxc4 is another significant option, but it immediately transposes to a major Catalan variation whose coverage begins in variation B of Chapter 6 on page 80." },
  { id: "c21-heading", type: "heading", status: "source-verified", sourceSpanId: ids(18, "left"), text: "C21) 6...Be7 7.dxc5 Bxc5", moveRefs: [ref("6...Be7", "c21-entry", 0), ref("7.dxc5", "c21-entry", 1), ref("Bxc5", "c21-entry", 2)] },
  { id: "c21-p18-right", type: "prose", status: "source-verified", sourceSpanId: ids(18, "right"), text: "8.a3!? In C1 I rejected the a2-a3 plan, but with the black knight committed to c6 the b2-b4 idea has more bite. 8.cxd5 is a good alternative: 8...exd5 9.Qc2 Bb6 10.Nc3 O-O transposes to C1, while 8...Nxd5 9.Qc2 also looks promising. 8...O-O. Other moves generally allow easy development. One way to alter the game is 8...dxc4 9.Qxd8+ Nxd8. 9...Kxd8 is worse: 10.Nbd2 c3 11.bxc3 Ke7 12.Nb3 Bd6 13.Nfd4 Bd7 14.Nb5 Be5 15.a4, when Black was already under pressure in Kochyev - Yurenko, St Petersburg 1999. 10.Ne5 Bd7 11.Nc3! 11.Nxc4 Bb5 is not so bad for Black." },
  { id: "c21-p19-left", type: "prose", status: "source-verified", sourceSpanId: ids(19, "left"), text: "11...Rc8 12.Rd1 h6!? was played in a remarkable game. Also possible is 12...Bc6N 13.Nxc4 Bxg2 14.Kxg2 Be7 15.Ne5 Nc6 16.Nxc6 Rxc6 17.Bf4 O-O 18.e4, when White retains solid pressure despite the simplifications. 13.Bf4 g5 14.Bd2 a6 15.Rac1 b5 16.Be1! Rh7 17.a4 b4 18.Ne4 Nxe4 19.Rxd7 Nd6 20.Rd1±. Black was crushed in Sharpe - Sibbald, corr. 2014. 9.b4 Bh6. The more popular 9...Be7 has scored less than 25% for Black. 10.Nbd2! It is important to get the move order right; 10.Bb2 allows 10...dxc4 11.Qc2 Bd7 12.Qxc4 Rc8 with minimal advantage." },
  { id: "c21-p19-right", type: "prose", status: "source-verified", sourceSpanId: ids(19, "right"), text: "After 10.Nbd2 Black's position is surprisingly unpleasant because of spatial inferiority and difficulty coordinating. 10...b6. After 10...Bd7 11.Bb2 Rc8 12.Rc1 a6 13.Nb3! dxc4 14.Rxc4 Nb8 15.Rxc8 Qxc8 in Kengis - Ginsburg, Zurich 2003, 16.Qd2N Bc6 17.Rc1 Qd8 18.Qxd8 Bxd8 19.Nfd2! Bxg2 20.Kxg2± gives Black an unpleasant endgame. 11.Bb2 Bb7 12.Rc1. Another example is 12...Rc8 13.Qa4! a5 14.b5N Nb8 15.cxd5 Rxc1 16.Rxc1 Bxd5 17.Nd4 Bxg2 18.Kxg2 with definite pressure. 12...dxc4 13.Nxc4 Qxd1N, a better try than 13...b5? 14.Nd4! Nxd4 15.Bxb7 Rb8 16.Na5, when Black was lost in Adhiban - Syed Anwar, Panaji 2012. 14.Rfxd1 Rac8 15.b5 Nb8 16.a4±. Black is doomed to passive defence." },
  { id: "c21-p20-left", type: "prose", status: "source-verified", sourceSpanId: ids(20, "left"), text: "10.Bb2! In contrast to the note above, 10.Nbd2 would be inaccurate here due to 10...e5!. 10...Qe7. 10...dxc4 is no problem after 11.Nbd2. 11.Nbd2 Rd8 12.Nb3!N. Almost everybody has played 12.Qc2 instead, but after 12...e5 White's position is less convincing. 12...e5 is therefore the logical main line; after a quiet move White simply develops the rooks and improves the position." },
  { id: "c21-p20-right", type: "prose", status: "source-verified", sourceSpanId: ids(20, "right"), text: "12...d4 is another forcing attempt, but 13.c5 Bc7 14.e3 is excellent for White. Against 14...e5, 15.exd4 e4 16.Ng5 Nxd4 17.Bxd4! Rxd4 18.Qb2 Be5 19.Rae1 wins Black's central pawn. 13.cxd5. 13.b5 also leads to favourable complications, but one line is enough. 13...Nxd5 14.b5! After 14.Nxe5 Nxe5 15.Bxd5 Be6 16.Bxe6 Rxd2 17.Bxe5 Rxe2 18.Bxf7+ Qxf7 19.Qxf7+ Kxf7, Black's activity should hold. 14...Na5 15.Qa4 Be6. Black must sacrifice the e-pawn: 15...f6? 16.e4 Nc7 17.Bc3 traps the knight, while 15...a6 16.Nxe5 Qe8 17.Qh4 also favours White. 16.Bxe5 Qd7 17.Ne4. Black does not have enough for the pawn." },

  { id: "c22-heading", type: "heading", status: "source-verified", sourceSpanId: ids(21, "left"), text: "C22) 6...cxd4 7.Nxd4", moveRefs: [ref("6...cxd4", "c22-entry", 0), ref("7.Nxd4", "c22-entry", 1)] },
  { id: "c22-p21-left", type: "prose", status: "source-verified", sourceSpanId: ids(21, "left"), text: "7.cxd5 is another decent option, but I would prefer to maintain the tension a little longer. 7...Bc5. Less challenging is 7...Be7 8.Nbc3 O-O 9.Be3! 9.cxd5 exd5 leads to a Tarrasch where Black exchanged on d4 prematurely, but the text move seems even stronger. It is hard to suggest a reply: 9...Ng4 10.cxd5 Nxe3 11.fxe3 exd5 12.Nxd5 Ne5 13.Qb3± left White an extra pawn and powerful knights in Modestov - Ananchenko, Samara 2003." },
  { id: "c22-p21-right", type: "prose", status: "source-verified", sourceSpanId: ids(21, "right"), text: "9...dxc4 was played in Ellers - Held, Fuerth 1998, and 10.Bxc6! bxc6 11.Nxc6 Qe8 12.Nxe7+ Qxe7 13.Qd4± gives White a lasting edge. 10.cxd5. There is nothing wrong with 10.Rc1, but the exchange is tempting because Black's next move reaches a standard Tarrasch with a full extra tempo for White. 10...exd5 11.Qa4! Bd7. 11...Na5 12.Qc2 followed by Rad1 is a dream position. 12.Nxd5 Nxd5 13.Bxd5 Nb4 14.Qb3 Qa5 15.Bf3±. White was a healthy pawn up in Benidze - Guliev, Malatya 2013. 8.Nb3. 8.Nxc6 bxc6 9.Qc2 is an interesting alternative, but strengthening Black's pawn centre is less logical. 8...Be7. The alternative 8...Bb6 9.Nc3!? O-O can transpose, while 9...dxc4 10.Nd2 looks nice for White." },
  { id: "c22-p22-left", type: "prose", status: "source-verified", sourceSpanId: ids(22, "left"), text: "Trying to hold the extra pawn is too risky: 10...Na5 11.b4 cxb3 12.Ba3! Bd7 13.axb3 Bc6 14.b4 Bxg2 15.bxa5 Bxa5 occurred in Perez - Montiel, Havana 1993, and 16.Nb5!N would have decided instantly. 10.Bg5. 10.cxd5 Nxd5 11.Nxd5 exd5 12.Qxd5 Bg4 gave Black significant compensation in Postny - Sebenik, Legnica 2013. 10...dxc4 11.Nd2 h6 12.Bxf6 Qxf6 13.Nxc4 Bc7. White has good queenside prospects; 14.Qa4N Bd7 15.Rfd1 Rfd8 16.Qa3 gives ongoing pressure. 9.cxd5 Nxd5. 9...exd5 10.Nc3 gives Black an unfavourable Tarrasch, for example 10...Be6 11.Be3 O-O 12.Qd2 Qd7 13.Rfd1 Rfd8 14.Rac1 Ne5 15.Nc5 Bxc5 16.Bxc5±, as in Karasek - Zavadil, Zlate Hory 2006." },
  { id: "c22-p22-right", type: "prose", status: "source-verified", sourceSpanId: ids(22, "right"), text: "10...O-O. After 10...Bf6 11.Qc1! O-O 12.Nc3 Nxc3 13.Bxc3 e5 in Burmakin - Laketic, Padova 2012, 14.Bxc6N bxc6 15.Bb4 Re8 16.Qxc6 wins a pawn. 11.Nc3 Nxc3. 11...Nf6 12.Rc1 e5 fails to solve Black's problems after 13.Be3 Be6 14.Nc5 Bxc5 15.Bxc5 Qxd1 16.Rfxd1+, when White's bishop pair is powerful." },
  { id: "c22-p23-left", type: "prose", status: "source-verified", sourceSpanId: ids(23, "left"), text: "11...Nb6 12.Ne4 Nd5 13.Rc1 Qb6 14.Qc2 h6 15.Nec5± gave White solid pressure in Azmaiparashvili - Zaichik, Philadelphia 1991. 12.Bxc3 Qb6 13.Nd4!? 13.Qd3N Rd8 14.Qe4 Bd7 15.Rfd1± is a safe alternative. After 13...Nb4 14.a3 Nd5, 15.Bxd5N exd5 16.Qd3± gives White a small but stable edge. 14.Nxc6! Rxd1 15.Nxe7+ Kf8 16.Rfxd1 Kxe7 17.Rac1 Bd7 18.Bd4. White had a great position in Jankovic - Cebalo, Croatia 2013, with full material equality for the queen once the b7- and/or g7-pawns fall, plus a strong initiative." },
  { id: "conclusion-heading", type: "heading", status: "source-verified", sourceSpanId: ids(23, "right"), text: "Conclusion" },
  { id: "conclusion", type: "variation", status: "source-verified", sourceSpanId: ids(23, "right"), title: "Conclusion", lineId: "c-conclusion-line-1", text: "4...g6 is odd-looking, but there is nothing much wrong with it. After 5.Bg2 Bg7 6.O-O O-O 7.Qc2 we have a typical Catalan with Black's bishop on an unusual square. White should be slightly better as long as he avoids early central conflict. 4...c6 is important: 5.Bg2 Nbd7 6.O-O Bd6 reaches a Closed Catalan structure where the bishop on d6 has pros and cons. White's most accurate order is 7.Nfd2! O-O 8.Nc3, when e2-e4 is hard to meet; 8...Bb4 is the only move that really makes White think, but Black still falls short of equality. Finally, 4...c5 is not popular among strong players, but it forces careful thought about Tarrasch transpositions. After 5.Bg2 Be7 we used the delayed development of Nc3; after 5...Nc6 6.O-O, Black did not equalize with either 6...Be7 or 6...cxd4. Capturing on c4 on move 5 or 6 transposes directly to Catalan variations in later chapters.", moveRefs: [] },
];
