/* This file is generated by `npm run chapters:sync`. Do not edit it by hand. */
import { CHAPTER_CONFIG as CHAPTER_1_CONFIG } from "./chapter-packages/chapter-1";
import { CHAPTER_CONFIG as CHAPTER_2_CONFIG } from "./chapter-packages/chapter-2";
import { CHAPTER_CONFIG as CHAPTER_3_CONFIG } from "./chapter-packages/chapter-3";

export const CHAPTER_CONFIGS = {
  "1": CHAPTER_1_CONFIG,
  "2": CHAPTER_2_CONFIG,
  "3": CHAPTER_3_CONFIG,
} as const;
