import crypto from "node:crypto";
import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { access, mkdir, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = path.resolve(appRoot, "..");
const packagesDirectory = path.join(appRoot, "app", "chapter-packages");
const manifestsDirectory = path.join(appRoot, "app", "chapter-manifests");
const catalogPath = path.join(appRoot, "app", "chapter-catalog.generated.ts");
const verifierPath = path.join(appRoot, "scripts", "verify-chapter-packages.ts");
const tsxCli = path.join(appRoot, "node_modules", "tsx", "dist", "cli.mjs");

function fail(message) {
  throw new Error(message);
}

function requireSupportedNode() {
  const [major, minor] = process.versions.node.split(".").map(Number);
  if (major < 22 || (major === 22 && minor < 13)) fail(`Node 22.13.0 or newer is required; current runtime is ${process.versions.node}.`);
}

async function exists(target) {
  try {
    await access(target);
    return true;
  } catch (error) {
    if (error?.code === "ENOENT") return false;
    throw error;
  }
}

async function chapterPackages() {
  const files = (await readdir(packagesDirectory))
    .map((name) => ({ name, match: /^chapter-(\d+)\.ts$/.exec(name) }))
    .filter((item) => item.match)
    .map((item) => ({ id: Number(item.match[1]), name: item.name }))
    .sort((left, right) => left.id - right.id);
  if (!files.length) fail("No chapter packages were found.");
  files.forEach((item, index) => {
    if (item.id !== index + 1) fail(`Chapter packages must be contiguous from 1; found chapter ${item.id} at position ${index + 1}.`);
  });
  return Promise.all(files.map(async (item) => {
    const manifestPath = path.join(manifestsDirectory, `chapter-${item.id}.json`);
    const manifest = JSON.parse(await readFile(manifestPath, "utf8").catch(() => fail(`${item.name} has no chapter-${item.id}.json manifest.`)));
    if (manifest.schemaVersion !== 1) fail(`chapter-${item.id}.json uses an unsupported schema version.`);
    if (manifest.id !== item.id) fail(`chapter-${item.id}.json does not match its package id.`);
    return { ...item, manifest };
  }));
}

function catalogSource(packages) {
  const ids = packages.map(({ id }) => `"${id}"`).join(", ");
  const summaries = packages.map(({ id, manifest }) => `  { id: "${id}", label: "Chapter ${id}", shortLabel: "Chapter ${id} lesson", printedRange: "printed pp.${manifest.source.printedStart}-${manifest.source.printedEnd}" },`).join("\n");
  const loaders = packages.map(({ id }) => `  "${id}": () => import("./chapter-packages/chapter-${id}").then((module) => module.CHAPTER_CONFIG),`).join("\n");
  return `/* This file is generated by \`npm run chapters:sync\`. Do not edit it by hand. */\nimport type { ChapterConfig, ChapterSummary } from "./chapter-definition";\n\nexport const CHAPTER_IDS = [${ids}] as const;\nexport type ChapterId = (typeof CHAPTER_IDS)[number];\n\nexport const CHAPTER_SUMMARIES = [\n${summaries}\n] as const satisfies readonly ChapterSummary[];\n\nexport function isChapterId(id: string): id is ChapterId {\n  return (CHAPTER_IDS as readonly string[]).includes(id);\n}\n\nconst CHAPTER_LOADERS: Record<ChapterId, () => Promise<ChapterConfig>> = {\n${loaders}\n};\n\nexport function loadChapter(id: ChapterId): Promise<ChapterConfig> {\n  return CHAPTER_LOADERS[id]();\n}\n`;
}

async function stagedPdfIds() {
  return (await readdir(repoRoot))
    .map((name) => /^Chapter(\d+)_Catalan\.pdf$/.exec(name))
    .filter(Boolean)
    .map((match) => Number(match[1]))
    .sort((left, right) => left - right);
}

async function syncRegistry({ checkOnly = false } = {}) {
  const packages = await chapterPackages();
  const expected = catalogSource(packages);
  const current = await readFile(catalogPath, "utf8").catch(() => "");
  if (current !== expected) {
    if (checkOnly) fail("The generated chapter catalog is stale. Run `npm run chapters:sync`.");
    const temporaryPath = `${catalogPath}.${process.pid}.tmp`;
    await writeFile(temporaryPath, expected, "utf8");
    await rename(temporaryPath, catalogPath);
    console.log(`Updated ${path.relative(appRoot, catalogPath)} for ${packages.length} chapters.`);
  } else if (!checkOnly) {
    console.log(`Chapter catalog is already current (${packages.length} chapters).`);
  }
  return packages;
}

function verifyPackages(chapterId) {
  const arguments_ = [tsxCli, verifierPath];
  if (chapterId) arguments_.push("--chapter", String(chapterId));
  if (process.argv.includes("--json")) arguments_.push("--json");
  const verification = spawnSync(process.execPath, arguments_, { cwd: appRoot, encoding: "utf8" });
  if (verification.stdout) process.stdout.write(verification.stdout);
  if (verification.stderr) process.stderr.write(verification.stderr);
  if (verification.status !== 0) fail(`Chapter verification failed${chapterId ? ` for Chapter ${chapterId}` : ""}.`);
}

async function checkSystem() {
  const packages = await syncRegistry({ checkOnly: true });
  const reviewKeys = new Set();
  for (const { id, manifest } of packages) {
    if (reviewKeys.has(manifest.review.storageKey)) fail(`Chapter ${id} reuses review key ${manifest.review.storageKey}.`);
    reviewKeys.add(manifest.review.storageKey);
  }
  verifyPackages();

  for (const relative of [
    path.join("app", "chapters", "[chapterId]", "page.tsx"),
    path.join("app", "chapters", "[chapterId]", "review", "page.tsx"),
    path.join("app", "chapters", "[chapterId]", "import", "page.tsx"),
  ]) {
    if (!(await exists(path.join(appRoot, relative)))) fail(`Shared route ${relative} is missing.`);
  }

  const staged = (await stagedPdfIds()).filter((id) => !packages.some((item) => item.id === id));
  const expectedNext = packages.at(-1).id + 1;
  if (staged.some((id) => id < expectedNext)) fail(`Found an unpublished PDF below the next chapter number ${expectedNext}.`);
  console.log(`Chapter system OK: ${packages.length} published; ${staged.length ? `staged ${staged.map((id) => `Chapter ${id}`).join(", ")}` : `next expected Chapter ${expectedNext}`}.`);
}

async function statusSystem() {
  const packages = await chapterPackages();
  const staged = (await stagedPdfIds()).filter((id) => !packages.some((item) => item.id === id));
  const expectedNext = packages.at(-1).id + 1;
  console.log(`Chapter status: ${packages.length} published (${packages.map(({ id }) => id).join(", ")}); ${staged.length ? `staged ${staged.map((id) => `Chapter ${id}`).join(", ")}` : `next expected Chapter ${expectedNext}`}.`);
}

function option(name) {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : undefined;
}

async function inspectPdf(pdfOption) {
  if (!pdfOption) fail("Pass a PDF with `--pdf <path>`.");
  const pdfPath = path.resolve(process.cwd(), pdfOption);
  const match = /^Chapter(\d+)_Catalan\.pdf$/.exec(path.basename(pdfPath));
  if (!match) fail("Chapter PDFs must be named ChapterN_Catalan.pdf.");
  const bytes = await readFile(pdfPath);
  const { getDocument } = await import("pdfjs-dist/legacy/build/pdf.mjs");
  const pdf = await getDocument({ data: new Uint8Array(bytes) }).promise;
  const firstPage = await pdf.getPage(1);
  const firstContent = await firstPage.getTextContent();
  const preview = firstContent.items.filter((item) => "str" in item).map((item) => item.str).join(" ").replace(/\s+/g, " ").trim().slice(0, 240);
  const result = {
    chapterId: Number(match[1]),
    filename: path.basename(pdfPath),
    bytes: bytes.byteLength,
    pageCount: pdf.numPages,
    sha256: crypto.createHash("sha256").update(bytes).digest("hex").toUpperCase(),
    firstPagePreview: preview,
  };
  await pdf.cleanup();
  return { pdfPath, bytes, result };
}

async function prepareChapter() {
  const { pdfPath, bytes, result } = await inspectPdf(option("--pdf"));
  const printedStart = Number(option("--printed-start"));
  if (!Number.isInteger(printedStart) || printedStart < 1) fail("Pass the first printed page number with `--printed-start <number>`.");
  const packages = await chapterPackages();
  const expectedId = packages.at(-1).id + 1;
  if (result.chapterId !== expectedId) fail(`The next publishable PDF is Chapter${expectedId}_Catalan.pdf, not Chapter ${result.chapterId}.`);

  const output = path.join(repoRoot, "tmp", "pdfs", `chapter-${result.chapterId}`);
  if (await exists(output)) {
    if (!process.argv.includes("--force")) fail(`${path.relative(repoRoot, output)} already exists. Remove it or rerun with --force.`);
    const safeRoot = path.join(repoRoot, "tmp", "pdfs") + path.sep;
    if (!output.startsWith(safeRoot)) fail("Refusing to replace evidence outside tmp/pdfs.");
    await rm(output, { recursive: true, force: true });
  }
  await mkdir(output, { recursive: true });
  const { getDocument } = await import("pdfjs-dist/legacy/build/pdf.mjs");
  const pdf = await getDocument({ data: new Uint8Array(bytes) }).promise;
  const pages = [];
  for (let index = 1; index <= pdf.numPages; index += 1) {
    const page = await pdf.getPage(index);
    const viewport = page.getViewport({ scale: 1 });
    const content = await page.getTextContent();
    const text = content.items.filter((item) => "str" in item).map((item) => item.str).join(" ").replace(/\s+/g, " ").trim();
    const printedPage = printedStart + index - 1;
    const textFile = `printed-${String(printedPage).padStart(2, "0")}.txt`;
    await writeFile(path.join(output, textFile), `${text}\n`, "utf8");
    const positioned = content.items
      .filter((item) => "str" in item && "transform" in item)
      .map((item) => ({ str: item.str, x: item.transform[4], top: viewport.height - item.transform[5] }));
    const regionText = (x0, x1) => positioned
      .filter((item) => item.x >= x0 && item.x < x1 && item.top >= 32 && item.top <= 650)
      .sort((left, right) => Math.abs(left.top - right.top) < 2 ? left.x - right.x : left.top - right.top)
      .map((item) => item.str)
      .join(" ")
      .replace(/\s+/g, " ")
      .trim();
    if (index === 1) {
      const fullTextFile = `printed-${String(printedPage).padStart(2, "0")}-full.txt`;
      await writeFile(path.join(output, fullTextFile), `${regionText(0, viewport.width)}\n`, "utf8");
      pages.push({ pageIndex: index - 1, printedPage, textFile, regions: [{ column: "full", textFile: fullTextFile }] });
    } else {
      const leftTextFile = `printed-${String(printedPage).padStart(2, "0")}-left.txt`;
      const rightTextFile = `printed-${String(printedPage).padStart(2, "0")}-right.txt`;
      await writeFile(path.join(output, leftTextFile), `${regionText(35, 237)}\n`, "utf8");
      await writeFile(path.join(output, rightTextFile), `${regionText(237, 440)}\n`, "utf8");
      pages.push({ pageIndex: index - 1, printedPage, textFile, regions: [{ column: "left", textFile: leftTextFile }, { column: "right", textFile: rightTextFile }] });
    }
  }
  await pdf.cleanup();
  const manifest = { ...result, printedStart, printedEnd: printedStart + result.pageCount - 1, sourcePath: path.relative(repoRoot, pdfPath), pages };
  await writeFile(path.join(output, "source-manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`, "utf8");

  const pathDirectories = (process.env.PATH ?? "").split(path.delimiter);
  const windowsCandidates = process.platform === "win32" ? [
    process.env.PDFTOPPM_PATH,
    ...pathDirectories.map((directory) => path.join(directory, "pdftoppm.exe")),
    process.env.USERPROFILE && path.join(process.env.USERPROFILE, ".cache", "codex-runtimes", "codex-primary-runtime", "dependencies", "native", "poppler", "Library", "bin", "pdftoppm.exe"),
    ...pathDirectories.map((directory) => path.join(directory, "pdftoppm.cmd")),
  ].filter(Boolean) : [process.env.PDFTOPPM_PATH, "pdftoppm"].filter(Boolean);
  const renderer = windowsCandidates.find((candidate) => process.platform !== "win32" || existsSync(candidate));
  if (!renderer) fail("PDF rendering failed: pdftoppm was not found. Install Poppler or set PDFTOPPM_PATH.");
  const render = spawnSync(renderer, ["-png", "-r", "144", pdfPath, path.join(output, "rendered")], { encoding: "utf8", shell: renderer.toLowerCase().endsWith(".cmd") });
  if (render.status !== 0) fail(`PDF rendering failed: ${(render.stderr || render.stdout || "pdftoppm unavailable").trim()}`);
  const renderedPages = (await readdir(output))
    .map((name) => ({ name, match: /^rendered-(\d+)\.png$/.exec(name) }))
    .filter((item) => item.match)
    .sort((left, right) => Number(left.match[1]) - Number(right.match[1]));
  if (renderedPages.length !== result.pageCount) fail(`Expected ${result.pageCount} rendered pages, found ${renderedPages.length}.`);
  for (const [index, rendered] of renderedPages.entries()) {
    const printedPage = printedStart + index;
    await rename(path.join(output, rendered.name), path.join(output, `printed-${String(printedPage).padStart(2, "0")}.png`));
  }
  console.log(`Prepared Chapter ${result.chapterId} evidence in ${path.relative(repoRoot, output)} (${result.pageCount} pages, printed ${manifest.printedStart}-${manifest.printedEnd}).`);
}

async function main() {
  requireSupportedNode();
  const command = process.argv[2];
  if (command === "sync") {
    verifyPackages();
    return syncRegistry();
  }
  if (command === "check") return checkSystem();
  if (command === "status") return statusSystem();
  if (command === "verify") return verifyPackages(Number(option("--chapter")) || undefined);
  if (command === "inspect") {
    const { result } = await inspectPdf(option("--pdf"));
    console.log(JSON.stringify(result, null, 2));
    return;
  }
  if (command === "prepare") return prepareChapter();
  fail("Use one of: status, check, verify [--chapter N], sync, inspect --pdf <path>, prepare --pdf <path> --printed-start <number>.");
}

main().catch((error) => {
  console.error(`Chapter system failed: ${error.message}`);
  process.exitCode = 1;
});
