import crypto from "node:crypto";
import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { access, mkdir, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { getDocument } from "pdfjs-dist/legacy/build/pdf.mjs";

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = path.resolve(appRoot, "..");
const packagesDirectory = path.join(appRoot, "app", "chapter-packages");
const registryPath = path.join(appRoot, "app", "chapter-registry.generated.ts");

function fail(message) {
  throw new Error(message);
}

async function exists(target) {
  try {
    await access(target);
    return true;
  } catch (error) {
    if (error?.code === "ENOENT") return false;
    throw error;
  }
}

async function chapterPackages() {
  const files = (await readdir(packagesDirectory))
    .map((name) => ({ name, match: /^chapter-(\d+)\.ts$/.exec(name) }))
    .filter((item) => item.match)
    .map((item) => ({ id: Number(item.match[1]), name: item.name }))
    .sort((left, right) => left.id - right.id);
  if (!files.length) fail("No chapter packages were found.");
  files.forEach((item, index) => {
    if (item.id !== index + 1) fail(`Chapter packages must be contiguous from 1; found chapter ${item.id} at position ${index + 1}.`);
  });
  return files;
}

function registrySource(packages) {
  const imports = packages.map(({ id }) => `import { CHAPTER_CONFIG as CHAPTER_${id}_CONFIG } from "./chapter-packages/chapter-${id}";`).join("\n");
  const entries = packages.map(({ id }) => `  "${id}": CHAPTER_${id}_CONFIG,`).join("\n");
  return `/* This file is generated by \`npm run chapters:sync\`. Do not edit it by hand. */\n${imports}\n\nexport const CHAPTER_CONFIGS = {\n${entries}\n} as const;\n`;
}

async function stagedPdfIds() {
  return (await readdir(repoRoot))
    .map((name) => /^Chapter(\d+)_Catalan\.pdf$/.exec(name))
    .filter(Boolean)
    .map((match) => Number(match[1]))
    .sort((left, right) => left - right);
}

async function syncRegistry({ checkOnly = false } = {}) {
  const packages = await chapterPackages();
  const expected = registrySource(packages);
  const current = await readFile(registryPath, "utf8").catch(() => "");
  if (current !== expected) {
    if (checkOnly) fail("The generated chapter registry is stale. Run `npm run chapters:sync`.");
    await writeFile(registryPath, expected, "utf8");
    console.log(`Updated ${path.relative(appRoot, registryPath)} for ${packages.length} chapters.`);
  } else if (!checkOnly) {
    console.log(`Chapter registry is already current (${packages.length} chapters).`);
  }
  return packages;
}

async function checkSystem() {
  const packages = await syncRegistry({ checkOnly: true });
  const reviewKeys = new Set();
  for (const { id, name } of packages) {
    const source = await readFile(path.join(packagesDirectory, name), "utf8");
    const requiredPatterns = [
      [new RegExp(`id:\\s*["']${id}["']`), `id ${id}`],
      [new RegExp(`label:\\s*["']Chapter ${id}["']`), `Chapter ${id} label`],
      [new RegExp(`filename:\\s*["']Chapter${id}_Catalan\\.pdf["']`), `Chapter${id}_Catalan.pdf filename`],
      [/expectedCanonicalHash\s*:/, "expected canonical hash"],
      [/defaultPosition\s*:/, "default position"],
      [/regions\s*:/, "import regions"],
    ];
    // Chapter 1 predates the full-chapter canonical snapshot; all succeeding chapters require it.
    for (const [pattern, label] of requiredPatterns) {
      if (id === 1 && label === "expected canonical hash") continue;
      if (!pattern.test(source)) fail(`${name} is missing its ${label}.`);
    }
    const reviewKey = source.match(/reviewKey:\s*["']([^"']+)["']/)?.[1];
    if (!reviewKey) fail(`${name} is missing a literal reviewKey.`);
    if (reviewKeys.has(reviewKey)) fail(`${name} reuses review key ${reviewKey}.`);
    reviewKeys.add(reviewKey);
    if (!(await exists(path.join(repoRoot, `Chapter${id}_Catalan.pdf`)))) fail(`Published Chapter ${id} has no root source PDF.`);
  }

  for (const relative of [
    path.join("app", "chapters", "[chapterId]", "page.tsx"),
    path.join("app", "chapters", "[chapterId]", "review", "page.tsx"),
    path.join("app", "chapters", "[chapterId]", "import", "page.tsx"),
  ]) {
    if (!(await exists(path.join(appRoot, relative)))) fail(`Shared route ${relative} is missing.`);
  }

  const staged = (await stagedPdfIds()).filter((id) => !packages.some((item) => item.id === id));
  const expectedNext = packages.at(-1).id + 1;
  if (staged.some((id) => id < expectedNext)) fail(`Found an unpublished PDF below the next chapter number ${expectedNext}.`);
  console.log(`Chapter system OK: ${packages.length} published; ${staged.length ? `staged ${staged.map((id) => `Chapter ${id}`).join(", ")}` : `next expected Chapter ${expectedNext}`}.`);
}

function option(name) {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : undefined;
}

async function inspectPdf(pdfOption) {
  if (!pdfOption) fail("Pass a PDF with `--pdf <path>`.");
  const pdfPath = path.resolve(process.cwd(), pdfOption);
  const match = /^Chapter(\d+)_Catalan\.pdf$/.exec(path.basename(pdfPath));
  if (!match) fail("Chapter PDFs must be named ChapterN_Catalan.pdf.");
  const bytes = await readFile(pdfPath);
  const pdf = await getDocument({ data: new Uint8Array(bytes) }).promise;
  const firstPage = await pdf.getPage(1);
  const firstContent = await firstPage.getTextContent();
  const preview = firstContent.items.filter((item) => "str" in item).map((item) => item.str).join(" ").replace(/\s+/g, " ").trim().slice(0, 240);
  const result = {
    chapterId: Number(match[1]),
    filename: path.basename(pdfPath),
    bytes: bytes.byteLength,
    pageCount: pdf.numPages,
    sha256: crypto.createHash("sha256").update(bytes).digest("hex").toUpperCase(),
    firstPagePreview: preview,
  };
  await pdf.cleanup();
  return { pdfPath, bytes, result };
}

async function prepareChapter() {
  const { pdfPath, bytes, result } = await inspectPdf(option("--pdf"));
  const printedStart = Number(option("--printed-start"));
  if (!Number.isInteger(printedStart) || printedStart < 1) fail("Pass the first printed page number with `--printed-start <number>`.");
  const packages = await chapterPackages();
  const expectedId = packages.at(-1).id + 1;
  if (result.chapterId !== expectedId) fail(`The next publishable PDF is Chapter${expectedId}_Catalan.pdf, not Chapter ${result.chapterId}.`);

  const output = path.join(repoRoot, "tmp", "pdfs", `chapter-${result.chapterId}`);
  if (await exists(output)) {
    if (!process.argv.includes("--force")) fail(`${path.relative(repoRoot, output)} already exists. Remove it or rerun with --force.`);
    const safeRoot = path.join(repoRoot, "tmp", "pdfs") + path.sep;
    if (!output.startsWith(safeRoot)) fail("Refusing to replace evidence outside tmp/pdfs.");
    await rm(output, { recursive: true, force: true });
  }
  await mkdir(output, { recursive: true });
  const pdf = await getDocument({ data: new Uint8Array(bytes) }).promise;
  const pages = [];
  for (let index = 1; index <= pdf.numPages; index += 1) {
    const page = await pdf.getPage(index);
    const viewport = page.getViewport({ scale: 1 });
    const content = await page.getTextContent();
    const text = content.items.filter((item) => "str" in item).map((item) => item.str).join(" ").replace(/\s+/g, " ").trim();
    const printedPage = printedStart + index - 1;
    const textFile = `printed-${String(printedPage).padStart(2, "0")}.txt`;
    await writeFile(path.join(output, textFile), `${text}\n`, "utf8");
    const positioned = content.items
      .filter((item) => "str" in item && "transform" in item)
      .map((item) => ({ str: item.str, x: item.transform[4], top: viewport.height - item.transform[5] }));
    const regionText = (x0, x1) => positioned
      .filter((item) => item.x >= x0 && item.x < x1 && item.top >= 32 && item.top <= 650)
      .sort((left, right) => Math.abs(left.top - right.top) < 2 ? left.x - right.x : left.top - right.top)
      .map((item) => item.str)
      .join(" ")
      .replace(/\s+/g, " ")
      .trim();
    if (index === 1) {
      const fullTextFile = `printed-${String(printedPage).padStart(2, "0")}-full.txt`;
      await writeFile(path.join(output, fullTextFile), `${regionText(0, viewport.width)}\n`, "utf8");
      pages.push({ pageIndex: index - 1, printedPage, textFile, regions: [{ column: "full", textFile: fullTextFile }] });
    } else {
      const leftTextFile = `printed-${String(printedPage).padStart(2, "0")}-left.txt`;
      const rightTextFile = `printed-${String(printedPage).padStart(2, "0")}-right.txt`;
      await writeFile(path.join(output, leftTextFile), `${regionText(35, 237)}\n`, "utf8");
      await writeFile(path.join(output, rightTextFile), `${regionText(237, 440)}\n`, "utf8");
      pages.push({ pageIndex: index - 1, printedPage, textFile, regions: [{ column: "left", textFile: leftTextFile }, { column: "right", textFile: rightTextFile }] });
    }
  }
  await pdf.cleanup();
  const manifest = { ...result, printedStart, printedEnd: printedStart + result.pageCount - 1, sourcePath: path.relative(repoRoot, pdfPath), pages };
  await writeFile(path.join(output, "source-manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`, "utf8");

  const pathDirectories = (process.env.PATH ?? "").split(path.delimiter);
  const windowsCandidates = process.platform === "win32" ? [
    process.env.PDFTOPPM_PATH,
    ...pathDirectories.map((directory) => path.join(directory, "pdftoppm.exe")),
    process.env.USERPROFILE && path.join(process.env.USERPROFILE, ".cache", "codex-runtimes", "codex-primary-runtime", "dependencies", "native", "poppler", "Library", "bin", "pdftoppm.exe"),
    ...pathDirectories.map((directory) => path.join(directory, "pdftoppm.cmd")),
  ].filter(Boolean) : [process.env.PDFTOPPM_PATH, "pdftoppm"].filter(Boolean);
  const renderer = windowsCandidates.find((candidate) => process.platform !== "win32" || existsSync(candidate));
  if (!renderer) fail("PDF rendering failed: pdftoppm was not found. Install Poppler or set PDFTOPPM_PATH.");
  const render = spawnSync(renderer, ["-png", "-r", "144", pdfPath, path.join(output, "rendered")], { encoding: "utf8", shell: renderer.toLowerCase().endsWith(".cmd") });
  if (render.status !== 0) fail(`PDF rendering failed: ${(render.stderr || render.stdout || "pdftoppm unavailable").trim()}`);
  const renderedPages = (await readdir(output))
    .map((name) => ({ name, match: /^rendered-(\d+)\.png$/.exec(name) }))
    .filter((item) => item.match)
    .sort((left, right) => Number(left.match[1]) - Number(right.match[1]));
  if (renderedPages.length !== result.pageCount) fail(`Expected ${result.pageCount} rendered pages, found ${renderedPages.length}.`);
  for (const [index, rendered] of renderedPages.entries()) {
    const printedPage = printedStart + index;
    await rename(path.join(output, rendered.name), path.join(output, `printed-${String(printedPage).padStart(2, "0")}.png`));
  }
  console.log(`Prepared Chapter ${result.chapterId} evidence in ${path.relative(repoRoot, output)} (${result.pageCount} pages, printed ${manifest.printedStart}-${manifest.printedEnd}).`);
}

async function main() {
  const command = process.argv[2];
  if (command === "sync") return syncRegistry();
  if (command === "check") return checkSystem();
  if (command === "inspect") {
    const { result } = await inspectPdf(option("--pdf"));
    console.log(JSON.stringify(result, null, 2));
    return;
  }
  if (command === "prepare") return prepareChapter();
  fail("Use one of: sync, check, inspect --pdf <path>, prepare --pdf <path> --printed-start <number>.");
}

main().catch((error) => {
  console.error(`Chapter system failed: ${error.message}`);
  process.exitCode = 1;
});
